const data = [
    {
      _id: "1",
      cover: "https://img-b.udemycdn.com/course/480x270/1565838_e54e_16.jpg",
      title: "The Complete 2023 Web Development Bootcamp",
      instructor: "Dr. Angela Yu",
      duration: " 65h 26m total length",
      rating: "281,504 ratings",
      enrollment: "950,015 students",
      description: "Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, MongoDB, Web3 and DApps",
      price: "$10.99",
    },
    {
        _id: "2",
        cover: "https://cdn.shopify.com/s/files/1/0716/7112/0152/products/the-complete-javascript-course.jpg?v=1678437925",
        title: "The Complete JavaScript Course 2023: From Zero to Expert!",
        instructor: "Jonas Schmedtmann",
        duration: "68h 59m total length",
        rating: "174,844 ratings",
        enrollment: "777,080 students",
        description: "The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one!",
        price: "$14.99",
      },
      {
        _id: "3",
        cover: "https://img-b.udemycdn.com/course/750x422/1754098_e0df_3.jpg",
        title: "The Data Science Course 2023: Complete Data Science Bootcamp",
        instructor: "tem ban lee",
        duration: "31h 51m total length",
        rating: "122,830 ratings",
        enrollment: "587,950 students",
        description: "Complete Data Science Training: Mathematics, Statistics, Python, Advanced Statistics in Python, Machine & Deep Learning",
        price: "$12.99",
      },
      {
        _id: "4",
        cover: "https://i.ytimg.com/vi/qle0UYFB8N0/maxresdefault.jpg",
        title: "Complete Web & Mobile Designer in 2023: UI/UX, Figma, +more",
        instructor: "Andrei Neagoie",
        duration: "28h 8m total length",
        rating: "20,640 ratings",
        enrollment: "111,278 students",
        description: "Become a Designer in 2023! Master Mobile and Web Design, User Interface + User Experience (UI/UX Design), HTML, and CSS",
        price: "$11.99",
      },
      {
        _id: "5",
        cover: "https://img-c.udemycdn.com/course/750x422/1672410_9ff1_5.jpg",
        title: "Node.js, Express, MongoDB & More: The Complete Bootcamp 2023",
        instructor: "Jonas Schmedtmann",
        duration: "58h 8m total length",
        rating: "20,60 ratings",
        enrollment: "11,279 students",
        description: "Node.js, Express, MongoDB & More: The Complete Bootcamp 2023",
        price: "$13.99",
      },
      {
        _id: "6",
        cover: "https://img-b.udemycdn.com/course/750x422/1778502_f4b9_12.jpg",
        title: "iOS & Swift - The Complete iOS App Development Bootcamp",
        instructor: "Dr. Angela Yu",
        duration: "49h 6m total length",
        rating: "204,6 ratings",
        enrollment: "11,279 students",
        description: "From Beginner to iOS App Developer with Just One Course! Fully Updated with a Comprehensive Module Dedicated to SwiftUI!",
        price: "$9.99",
      },
      {
        _id: "7",
        cover: "https://img-c.udemycdn.com/course/480x270/705264_caa9_13.jpg",
        title: "Modern React with Redux [2023 Update]",
        instructor: "Stephen Grider",
        duration: "39h 7m total length",
        rating: "304,60 ratings",
        enrollment: "41,279 students",
        description: "Master React and Redux Toolkit. Includes RTK Query, tons of custom hooks, and more! Course 100% Updated November 2022",
        price: "$10.99",
      },
      {
        _id: "8",
        cover: "https://img-b.udemycdn.com/course/750x422/2887266_c696_5.jpg",
        title: "Microservices with Node JS and React",
        instructor: "Stephen Grider",
        duration: "79h 7m total length",
        rating: "204,70 ratings",
        enrollment: "41,279 students",
        description: "Build, deploy, and scale an E-Commerce app using Microservices built with Node, React, Docker and Kubernetes",
        price: "$14.99",
      },
  ];
  